### ISSUE TITLE
Issue with CMakeLists

### ISSUE THREAD

**Issue by MitroiSabina** [edgeimpulse/voice-activated-microbit#5]
Hi @janjongboom,

I updated the new version from github but I still have some issues with it. I followed the guide on "How to build (Docker)" and, the command ```docker run --rm -v "%cd%":/data microbit_ei_build``` gives me this error:

![image](https://user-images.githubusercontent.com/23278237/107986331-83357280-6fd4-11eb-8be3-5fe6eb00bfb2.png)

Can you help me out?

**Comment by rajames** [comment]
Hi @MitroiSabina can you try remove the `build` directory and try the docker run command again?

**Comment by MitroiSabina** [comment]
Thank you @rajames! It works now. I was wondering, can I add more keywords than just one in MicrophoneInferenceTest.cpp?

**Comment by janjongboom** [comment]
@MitroiSabina Sure, add the checks here: https://github.com/edgeimpulse/voice-activated-microbit/blob/master/source/MicrophoneInferenceTest.cpp#L157

**Comment by MitroiSabina** [comment]
@janjongboom and @rajames thank you!
