### ISSUE TITLE
Issue with Edge Impulse Platform

### ISSUE THREAD

**Issue by MitroiSabina** [edgeimpulse/voice-activated-microbit#6]
Hello again!

I tried creating my data for my project by creating the data for the labels: happy, noise and unknown. But somehow, when I use the MFCC, I get this error:
![image](https://user-images.githubusercontent.com/23278237/108747771-7f5e9e80-7546-11eb-9ae7-8a2e4ab39615.png)
Have you ever experienced this error? I am not sure what am I supposed to change.
I only have 3 labels, and I have for 2 of them around 15 min and for the last one 5 min. I haven't changed the things around MFCC.
![image](https://user-images.githubusercontent.com/23278237/108748181-f8f68c80-7546-11eb-8d6e-f318df2cae70.png)
![image](https://user-images.githubusercontent.com/23278237/108748262-0f9ce380-7547-11eb-80c4-fb56cc015230.png)

**Comment by janjongboom** [comment]
Hi @MitroiSabina, the DSP container (which does the feature generation) was accidentally not marked as updated, and thus not rebuilt when we changed some stack frame calculations. We're rolling out a hotfix now!
